In [112]:
from pyscf import gto, lib
import numpy as np

np.set_printoptions(16, suppress=False, linewidth=300)

In [113]:
mol = gto.Mole(atom="O; H 1 0.94; H 1 0.94 2 104.5", basis="def2-TZVP").build()

## cint_prop

In [78]:
mol.has_ecp()

{}

In [79]:
mol.nbas

19

In [80]:
mol.atom_charge(0)

8

In [81]:
mol.nao_nr()

43

In [86]:
mol.nao_cart()

48

In [87]:
mol.nao_2c()

86

In [90]:
lib.fingerprint(mol.atom_coords())

-2.4358371781626658

In [91]:
mol.atom_nshells(0)

11

In [92]:
mol.bas_exps()

[array([27032.382631   ,  4052.3871392  ,   922.3272271  ,   261.24070989 ,    85.354641351,    31.035035245]),
 array([12.260860728 ,  4.9987076005]),
 array([1.1703108158]),
 array([0.46474740994]),
 array([0.18504536357]),
 array([63.274954801 , 14.627049379 ,  4.4501223456,  1.5275799647]),
 array([0.52935117943]),
 array([0.1747842127]),
 array([2.314]),
 array([0.645]),
 array([1.428]),
 array([34.061341 ,  5.1235746,  1.1646626]),
 array([0.32723041]),
 array([0.10307241]),
 array([0.8]),
 array([34.061341 ,  5.1235746,  1.1646626]),
 array([0.32723041]),
 array([0.10307241]),
 array([0.8])]

In [114]:
mol.aoslice_by_atom()

array([[ 0, 11,  0, 31],
       [11, 15, 31, 37],
       [15, 19, 37, 43]])

In [110]:
lib.fingerprint(mol.aoslice_by_atom())

-16.794909924641775